version: '3.8'

services:
  postgres:
    container_name: debatedor-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: unintegra
      PGDATA: /data/debatedor-pg
    volumes:
      - ./data/pg:/data/postgres